<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!--<div><h1><?php echo $this->escapeHtml($this->getMessage()); ?></h1>
    <br/><p><?php echo $this->escapeHtml($this->getName()); ?></p></div>-->


<div id="feedback" data-bind="scope:'feedback'">
    <br />
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#feedback": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "feedback": {
                            "component": "Smart_Feedback/js/feedback",
                            "config": {
                                "getFeedbackUrl": "<?php /* @escapeNotVerified */ echo $block->getFeedbackUrl(); ?>",
                                "email": "<?php /* @escapeNotVerified */ echo 'seeni@gmail.com'; ?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>